/*
* generated by Xtext
*/
package org.xtext.example.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.services.DefaultDSLGrammarAccess;

public class DefaultDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DefaultDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.example.parser.antlr.internal.InternalDefaultDSLParser createParser(XtextTokenStream stream) {
		return new org.xtext.example.parser.antlr.internal.InternalDefaultDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public DefaultDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DefaultDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
