/**
 * generated by Xtext
 */
package org.xtext.example.validation;

import org.xtext.example.validation.AbstractDefaultDSLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class DefaultDSLValidator extends AbstractDefaultDSLValidator {
}
