/*
 * generated by Xtext
 */
package org.xtext.example;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DefaultDSLRuntimeModule extends org.xtext.example.AbstractDefaultDSLRuntimeModule {

}
